services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_reflection_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ai_network

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - ai_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://user:password@db:5432/ai_reflection_db"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/ai_reflection_db"
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
      CHROMA_URL: "http://chromadb:8000"
      IS_DOCKER: "true"
    depends_on:
      - db
      - chromadb
    networks:
      - ai_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  db_data:
  chroma_data:
