
Table users {
  id String [pk]
  name String
  email String [unique]
  created_at DateTime [default: `now()`]
}

Table personas {
  id Int [pk]
  name String
  status_id Int
  created_at DateTime
}


// Lv1-1: 完全不変・定量可能
Table quantity_unchange_statuses {
  id Int [pk]
  persona_status_id Int [ref: - personas.status_id] // FK pointing to hub's status_id
  
  birth_date DateTime [note: '生年月日']
  gender String [note: '性別']
  blood_type String [note: '血液型']
  chronotype String [note: 'クロノタイプ（朝型/夜型）']
  bitterness_sense Int [note: '苦味感受性の強さ']
  intelligence Int [note: '相対的な知能。世代の中での割合を意味する。']
}

// Lv1-2: 完全不変・定量困難
Table semiquantity_unchange_statuses {
  id Int [pk]
  persona_status_id Int [ref: - personas.status_id]
  
  ethics Int [note: '倫理観 (0-100)']
  passion Int [note: '情熱・エネルギー (0-100)']
  curiosity Int [note: '好奇心 (0-100)']
  aggressiveness Int [note: '攻撃性・対立時の反応 (0-100)']
  extroversion Int [note: '外向性・社交性 (0-100)']
}

// Lv2: 不可逆的変化・定量可能
Table quantity_irreversible_statuses {
  id Int [pk]
  persona_status_id Int [ref: - personas.status_id]
  version Int
  
  height Float [note: '身長 (cm)']
  bone_density Float [note: '骨密度(g/cm^2)']
  grip_strength Float [note: '最大筋力（握力）(kg)']
  voice_pitch Float [note: '声の高さ（基本周波数）(Hz) 85-300']
  eyesight Float [note: '視力 0.1-2.0']
  hearing_ability Float [note: '聴力 (db) 0-70db']
  recorded_at DateTime [note: 'システム上の記録日時']
  recorded_for_persona DateTime [note: 'personaにとっての記録日時。過去の時間も入る。']
}

// Lv3-1: 可変・定量可能
Table quantity_reversible_statuses {
  id Int [pk]
  persona_status_id Int [ref: - personas.status_id]
  version Int
  
  weight Float [note: '体重 (kg)']
  body_fat_percentage Float [note: '体脂肪率 (%)']
  body_temperature Float [note: '体温(℃)']
  blood_sugar Float [note: '血糖値']// 気分や集中力の指標になる
  blood_pressure_sys Int [note: '収縮期血圧（上）']// 100以下なら朝に弱い
  blood_pressure_dia Int [note: '拡張期血圧（下）']
  sleep_time Float [note: '睡眠時間 (h)']
  sleep_quality Int [note: '睡眠の質 (1-10)']
  recorded_at DateTime [note: '記録日時']
}

// Lv3-2: 可変・定量困難
Table semiquantity_reversible_statuses {
  id Int [pk]
  persona_status_id Int [ref: - personas.status_id]
  version Int
  
  trust Int [note: 'ユーザーへの信頼度 (0-100)']
  friendliness Int [note: '親しみやすさ (0-100)']
  mood Int [note: '現在の気分 (0-100)']
  health Int [note: '総合的な健康状態 (0-100)']
  recorded_at DateTime [note: '記録日時']
}

Table chat_logs {
  id Int [pk]
  chat_id Int
  user_id Int [ref: > users.id]
  persona_id Int [ref: > personas.id]
  content String
}
